version: '3'

services:
  mongo:
    image: mongo:4.0.17-xenial
    container_name: 'petshop-mongo_db'
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - db-data:/data/db:delegated

  postgres:
    container_name: petshop-postgres_db
    image: postgres:9.6
    ports:
      - ${DATABASE_PORT}:5432
    expose:
      - '5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql

volumes:
  db-data:
  pgdata:
